site_name: OSG Education
site_url: https://opensciencegrid.github.io/education/
repo_url: https://github.com/opensciencegrid/education/
theme: readthedocs

extra_css:
  - css/extra.css

pages:
  - Home: 'index.md'

markdown_extensions:
  - admonition
  - codehilite
  - toc(permalink=true)
